# Generated by Django 5.1.5 on 2025-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuspage_manager', '0002_servicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
